# src/strategy/regime_engine.py

import pandas as pd


class ScalpingRegimeEngine:
    """
    15M Market Regime Evaluation Engine for Scalping.

    ============================================================
    PURPOSE
    ============================================================

    Consumes 15M market features generated by the FeatureEngineer
    and classifies the current market environment.

    The engine answers:

        "What type of market environment are we currently in?"

    It does NOT answer:

        "Should I enter a trade?"

    It does NOT place orders.

    It does NOT calculate position size.

    It does NOT make the final BUY / SELL decision.

    The regime engine sits between the 1H macro bias and the 5M
    setup engine.

    ============================================================
    MULTI-TIMEFRAME ARCHITECTURE
    ============================================================

        1H
         ↓
        MACRO BIAS
         ↓
        15M
         ↓
        MARKET REGIME + 15M DIRECTION
         ↓
        5M
         ↓
        SETUP
         ↓
        1M
         ↓
        ENTRY
         ↓
        COST / RISK
         ↓
        EXECUTION

    IMPORTANT ARCHITECTURAL RULE:

        1H bias and 15M regime are separate concepts.

        1H asks:

            "Which direction does the higher timeframe favor?"

        15M asks:

            "What environment is the market currently in?"

    The two should not be fused into one calculation.

    ============================================================
    REGIME STATES
    ============================================================

        TRENDING_EXPANSION
            The 15M market has directional structure and
            volatility is expanding relative to its baseline.

        RANGING_COMPRESSION
            Volatility is compressed and/or directional structure
            is sufficiently weak to classify the market as
            compressed rather than trending.

        HIGH_VOLATILITY_CHOP
            Volatility is abnormally high but the price/EMA
            structure does not provide sufficiently clean
            directional evidence.

        NEUTRAL
            Data is valid but the market does not strongly fit
            one of the above regimes.

        None
            Required data is unavailable or still warming up.

    IMPORTANT:

        NEUTRAL != missing data.

        NEUTRAL:
            The market was evaluated.

        None:
            The engine cannot reliably evaluate the market yet.

    ============================================================
    15M DIRECTION
    ============================================================

    Regime classification and direction are intentionally
    separated.

    Example:

        regime     = TRENDING_EXPANSION
        direction  = BULLISH

    or:

        regime     = TRENDING_EXPANSION
        direction  = BEARISH

    This allows the downstream setup engine to understand cases
    such as:

        1H = BULLISH
        15M = TRENDING_EXPANSION
        15M direction = BEARISH

    That may represent a pullback inside a higher-timeframe
    bullish structure.

    The regime engine should not destroy this information simply
    because the 15M direction differs from the 1H bias.

    ============================================================
    LOOK-AHEAD SAFETY
    ============================================================

    Volatility baselines are shifted by one candle before the
    rolling calculation.

    Therefore the current ATR is never used to construct the
    baseline against which the current ATR is judged.

    This prevents a subtle form of look-ahead contamination.

    ============================================================
    PERSISTENCE
    ============================================================

    Raw regime classification can change quickly.

    Example:

        TRENDING
        CHOP
        TRENDING
        CHOP

    A scalping system should not necessarily treat every single
    classification as a confirmed market-state transition.

    Therefore the engine uses a configurable persistence window.

    The state machine requires consecutive confirmation before
    switching into a new regime.

    This is intentionally kept small because the 15M regime must
    still react faster than the 1H macro bias.
    """

    # ============================================================
    # REGIME EVALUATION
    # ============================================================

    @staticmethod
    def evaluate_regime(
        df_15m: pd.DataFrame,
        bias_1h: pd.Series = None,
        atr_window: int = 20,
        min_separation_pct: float = 0.005,
        high_vol_threshold_mult: float = 2.2,
        min_atr_separation_ratio: float = 0.10,
        regime_persistence_window: int = 2,
    ) -> pd.Series:
        """
        Evaluate the confirmed 15M market regime.

        Parameters
        ----------
        df_15m : pd.DataFrame
            15M dataframe containing features generated by the
            FeatureEngineer.

        bias_1h : pd.Series, optional
            1H macro bias.

            IMPORTANT:
                This parameter is retained for compatibility with
                the previous engine interface.

            It is intentionally NOT used to determine whether the
            15M market is trending, ranging, or choppy.

            The 15M regime must remain independent of the 1H bias.

        atr_window : int
            Number of previous ATR observations used to establish
            the baseline volatility.

            With 15M candles:

                20 × 15 minutes = approximately 5 hours

            The current ATR is excluded from its own baseline.

        min_separation_pct : float
            Minimum percentage separation between EMA9 and EMA21
            required for meaningful directional structure.

        high_vol_threshold_mult : float
            Current ATR must exceed:

                baseline ATR × threshold

            to qualify as an extreme volatility spike.

        min_atr_separation_ratio : float
            Minimum EMA separation relative to ATR used as an
            additional normalized trend-structure measurement.

            Formula:

                abs(EMA9 - EMA21) / ATR

            This is intentionally configurable and should later
            be validated through backtesting.

        regime_persistence_window : int
            Number of consecutive raw classifications required
            before a new regime becomes confirmed.

            A value of 2 means the engine requires two consecutive
            observations before changing state.

        Returns
        -------
        pd.Series
            Confirmed regime states:

                TRENDING_EXPANSION
                RANGING_COMPRESSION
                HIGH_VOLATILITY_CHOP
                NEUTRAL

            None is returned for rows where the required data is
            unavailable.
        """

        # ========================================================
        # 0. BASIC INPUT VALIDATION
        # ========================================================

        if df_15m.empty:
            return pd.Series(
                dtype=object,
                index=df_15m.index,
                name="regime",
            )

        if atr_window < 1:
            raise ValueError("atr_window must be >= 1")

        if regime_persistence_window < 1:
            raise ValueError("regime_persistence_window must be >= 1")

        if min_separation_pct < 0:
            raise ValueError("min_separation_pct cannot be negative")

        if high_vol_threshold_mult <= 0:
            raise ValueError("high_vol_threshold_mult must be > 0")

        if min_atr_separation_ratio < 0:
            raise ValueError("min_atr_separation_ratio cannot be negative")

        # Work on a copy so the original dataframe is never
        # modified by the strategy layer.
        df = df_15m.copy()

        # ========================================================
        # 1. OUTPUT INITIALIZATION
        # ========================================================

        regime = pd.Series(
            None,
            index=df.index,
            dtype=object,
            name="regime",
        )

        # ========================================================
        # 2. REQUIRED FEATURE VALIDATION
        # ========================================================

        # These are the minimum measurements needed to classify
        # the 15M environment.
        #
        # EMA9 / EMA21:
        #     directional structure
        #
        # EMA separation:
        #     trend strength / compression
        #
        # EMA fast slope:
        #     directional momentum of the EMA structure
        #
        # ATR:
        #     volatility state
        #
        # close:
        #     price position relative to the trend structure

        required_columns = {
            "close",
            "ema_9",
            "ema_21",
            "ema_separation_pct",
            "ema_fast_slope",
            "atr",
        }

        missing_columns = required_columns - set(df.columns)

        if missing_columns:
            raise ValueError(
                "Missing required 15M feature columns: "
                + ", ".join(sorted(missing_columns))
            )

        # ========================================================
        # 3. WARM-UP & DATA-HYGIENE GUARD
        # ========================================================

        # Do NOT globally drop NaN rows.
        #
        # Indicator warm-up periods are expected.
        #
        # Instead, identify rows where this engine has enough
        # information to make a decision.

        valid_mask = (
            df["close"].notna()
            & df["ema_9"].notna()
            & df["ema_21"].notna()
            & df["ema_separation_pct"].notna()
            & df["ema_fast_slope"].notna()
            & df["atr"].notna()
            & (df["atr"] > 0)
        )

        if not valid_mask.any():
            return regime

        # ========================================================
        # 4. LOOK-AHEAD-SAFE ATR BASELINE
        # ========================================================

        # IMPORTANT:
        #
        # The current ATR is shifted out before calculating the
        # rolling baseline.
        #
        # Without the shift:
        #
        #     current ATR
        #          ↓
        #     contributes to baseline
        #          ↓
        #     baseline influences classification of current ATR
        #
        # With the shift:
        #
        #     previous ATR history
        #          ↓
        #     baseline
        #          ↓
        #     current ATR classification
        #
        # This is safer for both backtesting and live evaluation.

        baseline_atr = (
            df["atr"]
            .shift(1)
            .rolling(
                window=atr_window,
                min_periods=atr_window,
            )
            .mean()
        )

        valid_mask = valid_mask & baseline_atr.notna() & (baseline_atr > 0)

        if not valid_mask.any():
            return regime

        # ========================================================
        # 5. NORMALIZED EMA SEPARATION
        # ========================================================

        # Existing percentage separation remains important.
        #
        # However, percentage separation behaves differently
        # across instruments.
        #
        # Example:
        #
        #     EUR/USD
        #     XAU/USD
        #     BTC/USD
        #
        # A fixed percentage does not necessarily represent the
        # same amount of market movement.
        #
        # Therefore we additionally normalize EMA separation
        # against ATR.
        #
        # Formula:
        #
        #     abs(EMA9 - EMA21) / ATR
        #
        # This does NOT replace percentage separation yet.
        #
        # It gives us another measurement that can be researched
        # and calibrated later.

        ema_separation_atr_ratio = (df["ema_9"] - df["ema_21"]).abs() / df["atr"]

        # ========================================================
        # 6. VOLATILITY CONDITIONS
        # ========================================================

        # Current ATR above its previous baseline means volatility
        # is expanding.
        #
        # This alone does NOT mean the market is trending.

        atr_expanding = df["atr"] > baseline_atr

        # Extreme volatility spike.
        #
        # This is intentionally NOT automatically classified as
        # chop anymore.
        #
        # We first determine whether the price structure is clean.

        atr_spike = df["atr"] > baseline_atr * high_vol_threshold_mult

        # ========================================================
        # 7. TREND STRUCTURE CONDITIONS
        # ========================================================

        # Basic EMA alignment.

        bullish_ema_structure = df["ema_9"] > df["ema_21"]

        bearish_ema_structure = df["ema_9"] < df["ema_21"]

        # EMA slope confirms that the fast EMA is actually moving
        # in the same direction as the alignment.

        bullish_slope = df["ema_fast_slope"] > 0

        bearish_slope = df["ema_fast_slope"] < 0

        # Price position provides another layer of directional
        # confirmation.

        bullish_price_position = df["close"] > df["ema_9"]

        bearish_price_position = df["close"] < df["ema_9"]

        # ========================================================
        # 8. TREND STRENGTH / SEPARATION
        # ========================================================

        percentage_separation_ok = df["ema_separation_pct"].abs() >= min_separation_pct

        atr_normalized_separation_ok = (
            ema_separation_atr_ratio >= min_atr_separation_ratio
        )

        # Both measurements are used.
        #
        # This gives us:
        #
        #     absolute/percentage structure
        #                 +
        #     volatility-normalized structure
        #
        # rather than relying on only one measurement.

        meaningful_separation = percentage_separation_ok & atr_normalized_separation_ok

        # ========================================================
        # 9. CLEAN DIRECTIONAL STRUCTURE
        # ========================================================

        # A clean bullish structure requires:
        #
        #     EMA9 > EMA21
        #     positive fast EMA slope
        #     price above EMA9
        #     meaningful EMA separation

        clean_bullish_structure = (
            valid_mask
            & meaningful_separation
            & bullish_ema_structure
            & bullish_slope
            & bullish_price_position
        )

        # Same logic in the opposite direction.

        clean_bearish_structure = (
            valid_mask
            & meaningful_separation
            & bearish_ema_structure
            & bearish_slope
            & bearish_price_position
        )

        clean_directional_structure = clean_bullish_structure | clean_bearish_structure

        # ========================================================
        # 10. HIGH-VOLATILITY CHOP
        # ========================================================

        # IMPORTANT UPGRADE:
        #
        # Previous logic effectively treated:
        #
        #     ATR spike
        #         =
        #     HIGH_VOLATILITY_CHOP
        #
        # That is too simplistic.
        #
        # A large volatility expansion can occur during a genuine
        # directional breakout.
        #
        # Therefore:
        #
        #     HIGH VOLATILITY
        #             +
        #     CLEAN DIRECTIONAL STRUCTURE
        #             =
        #     potentially TRENDING_EXPANSION
        #
        # Whereas:
        #
        #     HIGH VOLATILITY
        #             +
        #     weak/conflicting structure
        #             =
        #     HIGH_VOLATILITY_CHOP
        #
        # This is a much more useful distinction.

        chop_condition = valid_mask & atr_spike & ~clean_directional_structure

        # ========================================================
        # 11. TRENDING EXPANSION
        # ========================================================

        # A trending expansion requires:
        #
        #     volatility expansion
        #     +
        #     meaningful directional structure
        #
        # Notice:
        #
        #     1H bias is NOT used here.
        #
        # This is intentional.
        #
        # The 15M regime engine describes the 15M market itself.

        trending_condition = (
            valid_mask & ~chop_condition & atr_expanding & clean_directional_structure
        )

        # ========================================================
        # 12. RANGING / COMPRESSION
        # ========================================================

        # Compression is identified through weak directional
        # structure and/or below-baseline volatility.
        #
        # We intentionally do not say:
        #
        #     low ATR = range
        #
        # because low volatility alone does not prove a range.
        #
        # Instead, the EMA structure is also considered.

        low_volatility = df["atr"] <= baseline_atr

        weak_structure = ~meaningful_separation

        ranging_condition = (
            valid_mask
            & ~chop_condition
            & ~trending_condition
            & (low_volatility | weak_structure)
        )

        # ========================================================
        # 13. RAW REGIME CLASSIFICATION
        # ========================================================

        raw_regime = pd.Series(
            None,
            index=df.index,
            dtype=object,
        )

        # Priority order matters.
        #
        # 1. Extreme volatility without clean structure
        # 2. Clean directional expansion
        # 3. Compression/range
        # 4. Valid but unclassified → NEUTRAL

        raw_regime.loc[chop_condition] = "HIGH_VOLATILITY_CHOP"

        raw_regime.loc[trending_condition] = "TRENDING_EXPANSION"

        raw_regime.loc[ranging_condition] = "RANGING_COMPRESSION"

        # Valid observations not classified by the above rules
        # remain genuine NEUTRAL states.

        neutral_mask = valid_mask & raw_regime.isna()

        raw_regime.loc[neutral_mask] = "NEUTRAL"

        # ========================================================
        # 14. REGIME PERSISTENCE / STATE MACHINE
        # ========================================================

        # A regime should not flip simply because one candle
        # temporarily satisfies a different condition.
        #
        # Example:
        #
        #     TRENDING
        #     TRENDING
        #     CHOP
        #     TRENDING
        #
        # With persistence = 2, the single CHOP observation does
        # not immediately replace the established TRENDING state.
        #
        # This is implemented as a small state machine rather than
        # a simple rolling label because we want to preserve the
        # previously confirmed state until a new state receives
        # enough consecutive confirmation.

        confirmed_regime = None

        candidate_regime = None
        candidate_count = 0

        for timestamp, current_raw_regime in raw_regime.items():

            # ----------------------------------------------------
            # Missing / unavailable data
            # ----------------------------------------------------

            if pd.isna(current_raw_regime):
                # We cannot evaluate this row.
                #
                # Do not invent a regime.
                #
                # Also do not use missing data as confirmation
                # for a state transition.

                regime.loc[timestamp] = None
                continue

            # ----------------------------------------------------
            # First valid regime observation
            # ----------------------------------------------------

            if confirmed_regime is None:
                if candidate_regime == current_raw_regime:
                    candidate_count += 1
                else:
                    candidate_regime = current_raw_regime
                    candidate_count = 1

                if candidate_count >= regime_persistence_window:
                    confirmed_regime = candidate_regime
                    candidate_regime = None
                    candidate_count = 0

                # Until the first regime is confirmed, do not
                # pretend that a single observation is enough.

                regime.loc[timestamp] = confirmed_regime

                continue

            # ----------------------------------------------------
            # Existing confirmed state
            # ----------------------------------------------------

            if current_raw_regime == confirmed_regime:

                # Current market agrees with established regime.
                #
                # Any pending transition is cancelled.

                candidate_regime = None
                candidate_count = 0

                regime.loc[timestamp] = confirmed_regime

                continue

            # ----------------------------------------------------
            # Potential regime transition
            # ----------------------------------------------------

            if candidate_regime == current_raw_regime:
                candidate_count += 1
            else:
                candidate_regime = current_raw_regime
                candidate_count = 1

            # ----------------------------------------------------
            # Confirm transition
            # ----------------------------------------------------

            if candidate_count >= regime_persistence_window:
                confirmed_regime = candidate_regime
                candidate_regime = None
                candidate_count = 0

            # Until transition confirmation, retain the previous
            # established regime.
            #
            # This is the key difference between a noisy raw
            # classifier and a confirmed operational regime.

            regime.loc[timestamp] = confirmed_regime

        return regime

    # ============================================================
    # 15M DIRECTION EVALUATION
    # ============================================================

    @staticmethod
    def evaluate_direction(
        df_15m: pd.DataFrame,
        min_separation_pct: float = 0.005,
        min_atr_separation_ratio: float = 0.10,
    ) -> pd.Series:
        """
        Evaluate the independent 15M directional state.

        This method intentionally does NOT use the 1H bias.

        It answers:

            "Which direction is the 15M structure currently
             pointing?"

        Returns:

            BULLISH
            BEARISH
            NEUTRAL
            None

        IMPORTANT:

            Direction is NOT the same thing as regime.

            Example:

                direction = BULLISH
                regime = RANGING_COMPRESSION

            is completely valid.

        A market can have a slight bullish directional structure
        while still being too compressed to classify as a trend.
        """

        if df_15m.empty:
            return pd.Series(
                dtype=object,
                index=df_15m.index,
                name="direction",
            )

        df = df_15m.copy()

        # ========================================================
        # 1. REQUIRED FEATURES
        # ========================================================

        required_columns = {
            "close",
            "ema_9",
            "ema_21",
            "ema_separation_pct",
            "ema_fast_slope",
            "atr",
        }

        missing_columns = required_columns - set(df.columns)

        if missing_columns:
            raise ValueError(
                "Missing required 15M feature columns: "
                + ", ".join(sorted(missing_columns))
            )

        direction = pd.Series(
            None,
            index=df.index,
            dtype=object,
            name="direction",
        )

        # ========================================================
        # 2. DATA VALIDITY
        # ========================================================

        valid_mask = (
            df["close"].notna()
            & df["ema_9"].notna()
            & df["ema_21"].notna()
            & df["ema_separation_pct"].notna()
            & df["ema_fast_slope"].notna()
            & df["atr"].notna()
            & (df["atr"] > 0)
        )

        # ========================================================
        # 3. ATR-NORMALIZED EMA SEPARATION
        # ========================================================

        ema_separation_atr_ratio = (df["ema_9"] - df["ema_21"]).abs() / df["atr"]

        meaningful_separation = (
            df["ema_separation_pct"].abs() >= min_separation_pct
        ) & (ema_separation_atr_ratio >= min_atr_separation_ratio)

        # ========================================================
        # 4. BULLISH STRUCTURE
        # ========================================================

        bullish = (
            valid_mask
            & meaningful_separation
            & (df["ema_9"] > df["ema_21"])
            & (df["ema_fast_slope"] > 0)
            & (df["close"] > df["ema_9"])
        )

        # ========================================================
        # 5. BEARISH STRUCTURE
        # ========================================================

        bearish = (
            valid_mask
            & meaningful_separation
            & (df["ema_9"] < df["ema_21"])
            & (df["ema_fast_slope"] < 0)
            & (df["close"] < df["ema_9"])
        )

        # ========================================================
        # 6. STATE ASSIGNMENT
        # ========================================================

        direction.loc[bullish] = "BULLISH"

        direction.loc[bearish] = "BEARISH"

        # Valid but non-directional observations are explicitly
        # NEUTRAL.

        neutral = valid_mask & direction.isna()

        direction.loc[neutral] = "NEUTRAL"

        return direction
