# src/Strategy/scalping_bias_engine.py

import pandas as pd


class ScalpingBiasEngine:
    """
    1H Macro Market Bias Evaluation Engine for Scalping.

    ============================================================
    PURPOSE
    ============================================================

    Consumes 1H features produced by the FeatureEngineer and
    determines the higher-timeframe directional state that the
    lower-timeframe scalping system should prefer.

    The engine answers ONE question:

        "What is the current 1H directional bias?"

    It does NOT answer:

        "Should I enter a trade?"

    Entry decisions belong to the lower layers of the system.

    ============================================================
    SCALPING TIMEFRAME ARCHITECTURE
    ============================================================

        1H
         ↓
        MACRO BIAS
         ↓
        15M
         ↓
        MARKET REGIME
         ↓
        5M
         ↓
        SETUP
         ↓
        1M
         ↓
        ENTRY

    Therefore this engine intentionally operates only on 1H data.

    ============================================================
    OUTPUT STATES
    ============================================================

        BULLISH
            The 1H structure supports a bullish directional bias.

        BEARISH
            The 1H structure supports a bearish directional bias.

        NEUTRAL
            The market was evaluated, but there is insufficient
            directional evidence to prefer either side.

    IMPORTANT:

        NEUTRAL is NOT the same thing as missing data.

        NEUTRAL:
            Data exists and was evaluated, but no directional
            edge was established.

        Missing / invalid:
            Required data does not exist yet, usually because
            indicators are still warming up.

    The engine returns an empty string/None-like state only where
    required data cannot be evaluated. For normal evaluated rows,
    the state is explicitly represented as NEUTRAL.

    ============================================================
    CORE BIAS LOGIC
    ============================================================

    Bullish bias requires:

        1. EMA9 > EMA21
        2. Fast EMA slope > 0
        3. Close > EMA9
        4. EMA separation exceeds the minimum threshold
        5. Required indicator data is valid

    Bearish bias requires the inverse:

        1. EMA9 < EMA21
        2. Fast EMA slope < 0
        3. Close < EMA9
        4. EMA separation exceeds the minimum threshold
        5. Required indicator data is valid

    ============================================================
    PERSISTENCE / DEBOUNCING
    ============================================================

    A single 1H candle should not immediately flip the macro bias.

    Example with persistence_window = 2:

        Candle 1 → bullish evidence
        Candle 2 → bullish evidence
                     ↓
                  BULLISH

    This reduces rapid state changes caused by temporary
    fluctuations around the EMA relationship.

    ============================================================
    SESSION HANDLING
    ============================================================

    Session restrictions are intentionally NOT used to determine
    whether the market itself is bullish or bearish.

    This is an architectural distinction:

        MARKET BIAS
            =
        what direction the market structure currently favors

        SESSION PERMISSION
            =
        whether the bot is allowed to trade at this time

    Session permission belongs later in the execution/risk path.

    All timestamps are expected to be interpreted in UTC.

    ============================================================
    LOOK-AHEAD SAFETY
    ============================================================

    This engine only consumes features available on the current
    1H candle.

    It does not inspect future candles and therefore does not
    introduce future information into the bias calculation.
    """

    # ========================================================
    # PUBLIC BIAS EVALUATION
    # ========================================================

    @staticmethod
    def evaluate_bias(
        df: pd.DataFrame,
        persistence_window: int = 2,
        min_separation_pct: float = 0.01,
    ) -> pd.Series:
        """
        Evaluate the 1H macro directional bias.

        Parameters
        ----------
        df : pd.DataFrame
            1H dataframe containing features generated by
            FeatureEngineer.

        persistence_window : int
            Number of consecutive qualifying candles required
            before a directional state becomes active.

            Example:

                persistence_window = 2

                bullish
                bullish
                    ↓
                BULLISH

        min_separation_pct : float
            Minimum absolute percentage separation between EMA9
            and EMA21 required to consider the market sufficiently
            directional.

            This is a configurable starting threshold for V1.
            It should later be validated independently for each
            instrument/asset class through backtesting.

        Returns
        -------
        pd.Series
            A series containing:

                "BULLISH"
                "BEARISH"
                "NEUTRAL"

            Invalid/warm-up rows remain None so that downstream
            logic can distinguish unavailable data from a genuine
            neutral market state.
        """

        # ====================================================
        # 0. BASIC INPUT VALIDATION
        # ====================================================

        if df.empty:
            return pd.Series(
                dtype=object,
                index=df.index,
                name="bias",
            )

        df = df.copy()

        # ----------------------------------------------------
        # Validate persistence parameter
        # ----------------------------------------------------

        if persistence_window < 1:
            raise ValueError("persistence_window must be >= 1")

        # ----------------------------------------------------
        # Validate required columns
        # ----------------------------------------------------

        required_columns = {
            "close",
            "ema_9",
            "ema_21",
            "ema_separation_pct",
            "ema_fast_slope",
            "atr",
        }

        missing_columns = required_columns - set(df.columns)

        if missing_columns:
            raise ValueError(
                "Missing required 1H feature columns: "
                + ", ".join(sorted(missing_columns))
            )

        # ====================================================
        # 1. INITIALIZE OUTPUT
        # ====================================================

        # None means:
        #
        #     "The required information is not currently
        #      available to evaluate this row."
        #
        # It is intentionally different from:
        #
        #     "NEUTRAL"
        #
        # which means the market was evaluated but did not
        # establish a directional bias.

        bias = pd.Series(
            None,
            index=df.index,
            dtype=object,
            name="bias",
        )

        # ====================================================
        # 2. WARM-UP & DATA HYGIENE GUARD
        # ====================================================

        # We require all features necessary for the current
        # bias calculation to be valid.
        #
        # ATR is included as a required market-volatility
        # measurement and data-validity check.
        #
        # We do NOT globally drop rows here because the feature
        # engine intentionally preserves warm-up rows.

        valid_mask = (
            df["ema_21"].notna()
            & df["ema_9"].notna()
            & df["atr"].notna()
            & df["ema_separation_pct"].notna()
            & df["ema_fast_slope"].notna()
            & df["close"].notna()
        )

        # If nothing is currently evaluable, return the
        # initialized result.
        if not valid_mask.any():
            return bias

        # ====================================================
        # 3. VOLATILITY / MARKET ACTIVITY GUARD
        # ====================================================

        # The bias engine should not become a full regime engine.
        #
        # Detailed volatility classification belongs to the
        # 15M regime engine.
        #
        # Therefore V1 uses ATR primarily as a validity guard.
        #
        # A future version may add ATR-normalized EMA separation:
        #
        #     abs(EMA9 - EMA21) / ATR
        #
        # This should be researched rather than arbitrarily added.

        volatility_data_ok = df["atr"] > 0

        valid_mask = valid_mask & volatility_data_ok

        # ====================================================
        # 4. EMA SEPARATION / CHOP FILTER
        # ====================================================

        # When EMA9 and EMA21 are extremely close together,
        # directional interpretation becomes less reliable.
        #
        # Example:
        #
        #     EMA9  = 1.08501
        #     EMA21 = 1.08500
        #
        # The market may technically satisfy EMA9 > EMA21,
        # but that does not necessarily represent meaningful
        # directional structure.
        #
        # Therefore a minimum separation is required.

        separation_ok = df["ema_separation_pct"].abs() >= min_separation_pct

        # ====================================================
        # 5. RAW BULLISH STRUCTURE
        # ====================================================

        # Bullish 1H structure requires confluence between:
        #
        #     EMA alignment
        #     EMA slope
        #     price position
        #     minimum EMA separation
        #
        # No entry decision is made here.

        raw_bullish = (
            valid_mask
            & separation_ok
            & (df["ema_9"] > df["ema_21"])
            & (df["ema_fast_slope"] > 0)
            & (df["close"] > df["ema_9"])
        )

        # ====================================================
        # 6. RAW BEARISH STRUCTURE
        # ====================================================

        raw_bearish = (
            valid_mask
            & separation_ok
            & (df["ema_9"] < df["ema_21"])
            & (df["ema_fast_slope"] < 0)
            & (df["close"] < df["ema_9"])
        )

        # ====================================================
        # 7. PERSISTENCE / DEBOUNCING FILTER
        # ====================================================

        # We require the raw directional condition to remain
        # valid for the configured number of consecutive candles.
        #
        # This reduces the chance of switching macro bias from
        # one temporary candle.
        #
        # Example with window = 2:
        #
        #     10:00 → bullish
        #     11:00 → bullish
        #                    ↓
        #                 BULLISH
        #
        # A single qualifying candle is therefore not enough
        # to establish a persistent state.

        persistent_bullish = (
            raw_bullish.rolling(
                window=persistence_window,
                min_periods=persistence_window,
            )
            .sum()
            .eq(persistence_window)
        )

        persistent_bearish = (
            raw_bearish.rolling(
                window=persistence_window,
                min_periods=persistence_window,
            )
            .sum()
            .eq(persistence_window)
        )

        # ====================================================
        # 8. STATE ASSIGNMENT
        # ====================================================

        # Assign confirmed directional states first.

        bias.loc[persistent_bullish] = "BULLISH"

        bias.loc[persistent_bearish] = "BEARISH"

        # ====================================================
        # 9. EXPLICIT NEUTRAL STATE
        # ====================================================

        # Rows that contain valid market information but do not
        # satisfy persistent bullish or bearish conditions are
        # genuine NEUTRAL states.
        #
        # This distinction is important:
        #
        #     None
        #         =
        #     insufficient/unavailable information
        #
        #     NEUTRAL
        #         =
        #     information available, but no directional bias

        evaluated_mask = valid_mask

        neutral_mask = evaluated_mask & ~persistent_bullish & ~persistent_bearish

        bias.loc[neutral_mask] = "NEUTRAL"

        # ====================================================
        # 10. RETURN
        # ====================================================

        return bias
